About Us Page & Improved Responsiveness
Cougar-AI/CougarAI-Website pull request #2
Opened 2023-07-13 21:44 UTC by tachorzy

This PR introduces the About Us page and includes a refactored homepage with better responsiveness and UI tweaks. 
- Added the About Us page `about/page.tsx` and **5 new components** found in `components/about`. 
- Updated `NavBar.tsx` with hover state styling.
- Adjusted homepage responsiveness on mobile and medium sized screens.
- Created `membership/page.tsx`, leaving it barebones for now, will work on this page in the next sprint. I don't want to make this one anymore bloated than it already is. 

**Next Tasks:**
- Start working on `membership/page.tsx` once I receive information from the club.
- Add  `contact/page.tsx`
- Get headshots from the club and refactor `OfficerCard.tsx` to work with different images.

2023-07-17 21:33 UTC, tachorzy commented
Small clarification: When I changed the favicon, I kept it as an `.ico` file in the `app` folder as seen in leerob's example code from Vercel found [here](https://github.com/leerob/leerob.io/tree/main/app). Rather than putting it in the `public` folder as we would be inclined to do before Next 13,

2023-07-24 01:03 UTC, bnleft commented
> Small clarification: When I changed the favicon, I kept it as an `.ico` file in the `app` folder as seen in leerob's example code from Vercel found [here](https://github.com/leerob/leerob.io/tree/main/app). Rather than putting it in the `public` folder as we would be inclined to do before Next 13.

Thanks for the clarification

2023-07-24 01:32 UTC, bnleft commented on util/officerInformation/officers.ts
A map would be better. It is hard to keep track of what the value at each index represent. It will become technical debt since we will be hardcoding the index value.

2023-07-24 17:09 UTC, bnleft requested changes

2023-07-24 17:09 UTC, bnleft commented on app/about/page.tsx
Extract into functional components like AboutUsInfoSection and OfficerSection - this makes it easier to trace parts of the page

2023-07-24 17:09 UTC, bnleft commented on components/homepage/Logo.tsx
nitpick: because there are no nest elements within the `Image` tags, we can treat them as singletons and they can end with `/>`

2023-07-24 17:36 UTC, tachorzy commented
Alright those changes should be more or less up! Let me know if I missed anything, and thanks again for spotting the conventions I overlooked!

2023-07-29 18:25 UTC, bnleft approved these changes
Thanks for changes - like the meaningful comments you made

2023-07-29 18:25 UTC, bnleft commented on components/about/AboutUsInfoSection.tsx
> +// update this content/information with better branding.
np: (future reference) start comments like these with `TODO:`

2023-07-29 18:32 UTC, merged